apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-govbot-frontend-deployment
  namespace: mlscopers
  labels:
    app: ai-govbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-govbot-frontend
  template:
    metadata:
      namespace: mlscopers
      labels:
        app: ai-govbot-frontend
    spec:
      containers:
      - name: frontend
        image: us-east1-docker.pkg.dev/ai-govbot-project/ai-govbot-repo/ai-govbot-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_API_URL # Name the variable
          value: "http://ai-govbot-backend-service.mlscopers.svc.cluster.local:8000" # Internal DNS name and port
        # --- End ADD ---