apiVersion: v1
kind: Service
metadata:
  name: ai-govbot-frontend-service # Service name (can be different from backend)
spec:
  selector:
    app: ai-govbot-frontend         # Selects pods managed by the frontend Deployment
  ports:
  - protocol: TCP
    port: 80                        # Port the external Load Balancer listens on
    targetPort: 8501                # Port on the frontend pods (Streamlit)
  type: LoadBalancer               # Exposes the service externally via GCP LB