apiVersion: v1
kind: Service
metadata:
  name: ai-govbot-backend-service
  namespace: mlscopers # Service name used by frontend
spec:
  selector:
    app: ai-govbot-backend         # Selects pods managed by the backend Deployment
  ports:
  - name: http-fastapi
    protocol: TCP
    port: 8000                     # Port the service listens on internally
    targetPort: 8000               # Port on the pods to forward traffic to
    #add 8001 port for health check
  - name: http-mlflow
    protocol: TCP
    port: 8001                     # Port the service listens on internally
    targetPort: 8001               # Port on the pods to forward traffic to
  type: LoadBalancer                  # Only expose internally within the cluster