apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-govbot-backend-deployment
  namespace: mlscopers
  labels:
    app: ai-govbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-govbot-backend
  template:
    metadata:
      namespace: mlscopers
      labels:
        app: ai-govbot-backend
    spec:
      # --- Add this section if your Docker Hub repo is PRIVATE ---
      # imagePullSecrets:
      # - name: dockerhub-secret # You'll create this secret later if needed
      containers:
      - name: backend
        # --- CHANGE THIS LINE ---
        image: rixirx/harvey-backend:v1 # Use Docker Hub path ${{ secrets.DOCKERHUB_USERNAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        # Add other env vars, resources, volumes as before
      # Add volumes, serviceAccountName as before