apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-govbot-backend-deployment
  namespace: mlscopers
  labels:
    app: ai-govbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-govbot-backend
  template:
    metadata:
      namespace: mlscopers
      labels:
        app: ai-govbot-backend
    spec:
      containers:
      - name: backend
        image: us-east1-docker.pkg.dev/ai-govbot-project/ai-govbot-repo/ai-govbot-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: LANGFUSE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: LANGFUSE_SECRET_KEY
        - name: LANGFUSE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: LANGFUSE_PUBLIC_KEY
        - name: LANGFUSE_HOST
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: LANGFUSE_HOST
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/gcp/key.json
        volumeMounts:
        - name: gcp-sa-volume
          mountPath: /secrets/gcp
          readOnly: true
      volumes:
      - name: gcp-sa-volume
        secret:
          secretName: gcp-secret
