apiVersion: v1
kind: Service
metadata:
  name: ai-govbot-backend-service # Service name used by frontend
spec:
  selector:
    app: ai-govbot-backend         # Selects pods managed by the backend Deployment
  ports:
  - protocol: TCP
    port: 8000                     # Port the service listens on internally
    targetPort: 8000               # Port on the pods to forward traffic to
  type: ClusterIP                  # Only expose internally within the cluster