name: Langfuse Error Monitoring

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  monitor:
    runs-on: ubuntu-latest
    outputs:
      send_alert: ${{ steps.monitoring.outputs.send_alert }}
      error_count: ${{ steps.monitoring.outputs.error_count }}
      trace_count_threshold: ${{ steps.monitoring.outputs.trace_count_threshold }}
      time_window_hours: ${{ steps.monitoring.outputs.time_window_hours }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langfuse
          # Add any other dependencies your script requires
          
      - name: Run monitoring script
        id: monitoring
        env:
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_HOST: ${{ secrets.LANGFUSE_HOST }}
          TRACE_COUNT_THRESHOLD: ${{ vars.TRACE_COUNT_THRESHOLD || '2' }}
          TIME_WINDOW_HOURS: ${{ vars.TIME_WINDOW_HOURS || '12' }}
        run: |
          # Run the monitoring script and capture its output
          OUTPUT=$(python src/main/langfuse_monitoring.py)
          
          # Check if trace count exceeded threshold
          if echo "$OUTPUT" | grep -q "Trace count exceeded threshold"; then
            echo "send_alert=true" >> $GITHUB_OUTPUT
            ERROR_COUNT=$(echo "$OUTPUT" | grep "Current trace count:" | cut -d':' -f2 | cut -d',' -f1 | xargs)
            echo "error_count=$ERROR_COUNT" >> $GITHUB_OUTPUT
            echo "trace_count_threshold=${{ vars.TRACE_COUNT_THRESHOLD || '2' }}" >> $GITHUB_OUTPUT
            echo "time_window_hours=${{ vars.TIME_WINDOW_HOURS || '12' }}" >> $GITHUB_OUTPUT
          else
            echo "send_alert=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Send email alert
        if: steps.monitoring.outputs.send_alert == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Errors in HARVEY exceeded Threshold - Langfuse"
          body: |
            Langfuse Error Monitoring Alert
            
            ${{ steps.monitoring.outputs.error_count }} errors were detected in the Langfuse observations over the past ${{ steps.monitoring.outputs.time_window_hours }} hours.
            
            This exceeds the configured threshold of ${{ steps.monitoring.outputs.trace_count_threshold }}.
            
            Please check your Langfuse dashboard for more details.
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_USERNAME }}
          secure: true  # Use TLS