name: Build and Deploy AI-GovBot to GKE (Dev Branch)

on:
  push:
    branches:
      - sanjana-dev # Trigger on pushes to the 'dev' branch
    paths:
      # Trigger only if relevant source or config files change
      - 'src/**'
      - 'deployment_scripts/**'
      - '.github/workflows/model-deploy.yml'
  workflow_dispatch:

env:
  PROJECT_ID: data-pipeline-deployment-trial
  ZONE: us-east1-d 
  CLUSTER_NAME: ai-govbot-cluster
  NAMESPACE: mlscopers
  API_KEY_PLACEHOLDER: "__API_KEY_PLACEHOLDER__"
  # --- Define GAR image names ---
  GAR_LOCATION: us-east1 
  GAR_REPOSITORY_NAME: ai-govbot-repo 
  BACKEND_IMAGE_NAME: us-east1-docker.pkg.dev/data-pipeline-deployment-trial/ai-govbot-repo/ai-govbot-backend:v1
  FRONTEND_IMAGE_NAME: us-east1-docker.pkg.dev/data-pipeline-deployment-trial/ai-govbot-repo/ai-govbot-frontend:v1
  # Define K8s manifest paths
  NAMESPACE_FILE: deployment_scripts/model-deployment/k8s-namespace.yaml
  BACKEND_DEPLOYMENT_FILE: deployment_scripts/model-deployment/backend/k8s-deployment.yaml
  BACKEND_SERVICE_FILE: deployment_scripts/model-deployment/backend/k8s-service.yaml
  FRONTEND_DEPLOYMENT_FILE: deployment_scripts/model-deployment/frontend/k8s-deployment.yaml
  FRONTEND_SERVICE_FILE: deployment_scripts/model-deployment/frontend/k8s-service.yaml
  # Define Dockerfile paths
  BACKEND_DOCKERFILE: deployment_scripts/model-deployment/backend/Dockerfile
  FRONTEND_DOCKERFILE: deployment_scripts/model-deployment/frontend/Dockerfile

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Authenticate to Google Cloud ---
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # --- ADD Step to Configure Docker for GAR ---
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --project=data-pipeline-deployment-trial

      # --- Set Full Image Name Environment Variables (uses updated names from env block) ---
      - name: Set Full Image Names
        run: |
          echo "Using Backend Image: ${{ env.BACKEND_IMAGE_NAME }}"
          echo "Using Frontend Image: ${{ env.FRONTEND_IMAGE_NAME }}"
    

      # # --- Build and Push Steps (use the same buildx steps, they now target GAR) ---
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and Push Backend Image to GAR
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ${{ env.BACKEND_DOCKERFILE }}
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ env.BACKEND_IMAGE_NAME }} # Pushes to the GAR path

      # - name: Build and Push Frontend Image to GAR
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ${{ env.FRONTEND_DOCKERFILE }}
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ env.FRONTEND_IMAGE_NAME }} # Pushes to the GAR path

      # # --- Get GKE Credentials ---
      # - name: Get GKE Cluster Credentials
      #   run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project data-pipeline-deployment-trial

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.ZONE }} 
          project_id: ${{ env.PROJECT_ID }}


      # --- Inject API Key Secret from github secrets ---
      - name: Create temporary .env file
        run: |
          echo "Creating temporary .env file..."
          # Write the secret value into the .env file in KEY=VALUE format
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo ".env file created."
          # Optional: cat .env # Use for debugging only, hides secrets in logs by default

      - name: Create/Update Kubernetes OpenAI Secret
        run: |
          echo "Creating/Updating Kubernetes secret 'openai-secret' from .env file..."
          kubectl create secret generic openai-secret \
            --from-env-file=.env \
            --namespace=${{ env.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -
          echo "Kubernetes secret 'openai-secret' processed."


      # --- Apply K8s Manifests ---
      - name: Deploy to GKE
        run: |
          echo "Applying Kubernetes manifests to namespace: ${{ env.NAMESPACE }}"

          echo "Applying Namespace: ${{ env.NAMESPACE_FILE }}"
          kubectl apply -f ${{ env.NAMESPACE_FILE }}

          echo "Applying Backend Deployment: ${{ env.BACKEND_DEPLOYMENT_FILE }}"
          kubectl apply -f  ${{ env.BACKEND_DEPLOYMENT_FILE }} -n ${{ env.NAMESPACE }}
          echo "Applying Backend Service: ${{ env.BACKEND_SERVICE_FILE }}"
          kubectl apply -f ${{ env.BACKEND_SERVICE_FILE }} -n ${{ env.NAMESPACE }}

          echo "Applying Frontend Deployment: ${{ env.FRONTEND_DEPLOYMENT_FILE }}"
          kubectl apply -f ${{ env.FRONTEND_DEPLOYMENT_FILE }} -n ${{ env.NAMESPACE }}
          echo "Applying Frontend Service: ${{ env.FRONTEND_SERVICE_FILE }}"
          kubectl apply -f ${{ env.FRONTEND_SERVICE_FILE }} -n ${{ env.NAMESPACE }}

      # --- Verify Deployment Rollout ---
      - name: Verify Deployment Rollout
        run: |
          echo "Waiting for deployments to complete..."
          kubectl rollout status deployment/ai-govbot-backend-deployment -n ${{ env.NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/ai-govbot-frontend-deployment -n ${{ env.NAMESPACE }} --timeout=5m
          echo "Deployment successful!"
          echo "Verifying services..."
          kubectl get services -n ${{ env.NAMESPACE }}