name: Run Unit Tests

on:
  push:
    branches:
      - ash-dev
  pull_request:
    branches:
      - ash-dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          # Ensure curl is installed
          sudo apt-get update
          sudo apt-get install -y curl
          # Download and install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          # Verify installation
          docker-compose --version

      - name: Build Docker image
        run: docker-compose -f docker-compose.yaml build

      - name: Run tests in a separate Docker container
        run: |
          # Create a temporary container to run tests, mounting the project directory
          docker run --rm \
            -v ${PWD}:/app \
            -w /app \
            apache/airflow:2.10.5 \
            bash -c "pip install -r data/data-pipeline/requirements.txt && PYTHONPATH=data/data-pipeline pytest tests/unit/ -v"