name: Run Unit Tests

on:
  push:
    branches:
      - ash-dev
      - dhanashree-dev
      - rishi-dev
      - sanjana-dev
      - vedant-dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run RAG tests
        run: |
            pytest tests/rag_pipeline_unit/ -v

      - name: Run Data Pipeline tests
        run: |
          pytest tests/unit/ -v

  notify:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify Success
        if: needs.test.result == 'success'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Pipeline Passed - Ready to Merge to Staging"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            All tests have passed. The PR can be merged to staging.
            
            Pull Request: ${{ github.event.pull_request.html_url }}
            
      - name: Notify Failure
        if: needs.test.result == 'failure'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Pipeline Failed"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Some tests have failed. Please check the logs.
            
            Pull Request: ${{ github.event.pull_request.html_url }}