name: Run Unit Tests

on:
  push:
    branches:
      - ash-dev
  pull_request:
    branches:
      - ash-dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match the Python version in your Docker container or project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data/data-pipeline/requirements.txt

      - name: Run unit tests
        run: |
          PYTHONPATH=data/data-pipeline pytest tests/unit/ -v