name: Run Unit Tests

on:
  push:
    branches:
      - ash-dev
      - dhanashree-dev
      - rishi-dev
      - sanjana-dev
      - vedant-dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/data/data-pipeline/dags
          pytest tests/unit/ -v