name: Run Unit Tests

on:
  push:
    branches:
      - ash-dev
  pull_request:
    branches:
      - ash-dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data/data-pipeline/requirements.txt

      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)/data/data-pipeline/dags
          python -m unittest discover tests/unit/ -v

      - name: Upload coverage reports to Codecov (optional)
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true